"""
simquery/runners/heat_runner.py
====================================
Master heater/cooler template — used by LLM #2 code-generation pipeline.
Mirrors flash_master.py exactly in structure.

The top section (DWSIM init → topology → solve) is FIXED.
The bottom section (OUTPUT BLOCK) is generated by LLM #2 at runtime.

Supported modes:
  - "heater"  : FEED → Heater  → OUT  (raise T to T_out_C)
  - "cooler"  : FEED → Cooler  → OUT  (lower T to T_out_C)

Input JSON format (from LLM #1):
{
  "task_type":        "heat",
  "heat_mode":        "heater" | "cooler",
  "components":       {"Propane": 0.5, "n-Butane": 0.5},
  "feed": {
    "flow_kmol_h":    100.0,
    "temperature_C":  60.0,
    "pressure_bar":   14.0
  },
  "outlet": {
    "temperature_C":  120.0,
    "pressure_drop_bar": 0.0    ← optional, defaults to 0.0
  },
  "property_package": "PR",
  "user_request":     "<original user question>"
}

CLI usage (for testing without LLM #2):
  python simquery/runners/heat_runner.py <path_to_task.json>
"""

import json
import os
import sys
import argparse

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.abspath(os.path.join(_HERE, "..", ".."))
sys.path.insert(0, _ROOT)

DWSIM_PATH = r"C:\Users\terrbear\AppData\Local\DWSIM"
OUTPUT_DIR  = os.path.join(_ROOT, "output")

PACKAGE_ALIASES = {
    "PENG-ROBINSON": "PR", "PENGROBINSON": "PR", "PENG ROBINSON": "PR",
    "PR": "PR", "NRTL": "NRTL", "SRK": "SRK",
    "SOAVE-REDLICH-KWONG": "SRK", "UNIQUAC": "UNIQUAC",
    "IDEAL": "IDEAL", "RAOULT": "IDEAL",
    "STEAM": "STEAM", "STEAM TABLES": "STEAM",
}

POLAR_COMPONENTS = {
    "WATER", "ETHANOL", "METHANOL", "ACETONE", "ACETIC ACID",
    "ISOPROPANOL", "1-PROPANOL", "N-PROPANOL",
}


def _normalize_package(pkg_str: str) -> str:
    key = pkg_str.upper().replace("-", "").replace(" ", "")
    for alias_key, val in PACKAGE_ALIASES.items():
        if alias_key.replace("-", "").replace(" ", "") == key:
            return val
    return pkg_str


def _auto_select_package(comp_list: list) -> str:
    if any(c.upper() in POLAR_COMPONENTS for c in comp_list):
        return "NRTL"
    return "PR"


# ─────────────────────────────────────────────────────────────────────────────
#  STREAM RESULT EXTRACTOR  (same as flash_master)
# ─────────────────────────────────────────────────────────────────────────────

def _extract_stream(stream_obj, stream_name: str, comp_names: list) -> dict:
    def _get(val):
        if val is None:
            return 0.0
        try:
            return float(val)
        except TypeError:
            try:
                return float(val.GetValueOrDefault())
            except Exception:
                return 0.0

    p0 = stream_obj.Phases[0].Properties
    p2 = stream_obj.Phases[2].Properties

    result = {
        "stream":           stream_name,
        "T_K":              round(_get(p0.temperature), 4),
        "T_C":              round(_get(p0.temperature) - 273.15, 4),
        "P_Pa":             round(_get(p0.pressure), 2),
        "P_bar":            round(_get(p0.pressure) / 1e5, 4),
        "molar_flow_molh":  round(_get(p0.molarflow) * 3600, 4),
        "mass_flow_kgh":    round(_get(p0.massflow) * 3600, 4),
        "enthalpy_kJkmol":  round(_get(p0.enthalpy) * 1000, 4),
        "vapor_fraction":   round(_get(p2.molarfraction), 6),
    }

    for comp_name in comp_names:
        try:
            xval = _get(stream_obj.Phases[0].Compounds[comp_name].MoleFraction)
        except Exception:
            xval = 0.0
        result[f"x_{comp_name}"] = round(xval, 6)

    return result


# ─────────────────────────────────────────────────────────────────────────────
#  FIXED TOPOLOGY: HEATER / COOLER
#  FEED → Heater/Cooler → OUT
# ─────────────────────────────────────────────────────────────────────────────

def _build_heat(task: dict, interf, sim, comp_names: list, pkg_tag: str):
    """
    Builds and wires the heater or cooler flowsheet.
    Returns (feed_result_dict, feed_obj, outlet_obj).
    """
    from DWSIM.Interfaces.Enums.GraphicObjects import ObjectType
    from DWSIM.UnitOperations import UnitOperations as DWSIMUnitOps
    from DWSIM.GlobalSettings import Settings

    feed_cfg   = task["feed"]
    outlet_cfg = task["outlet"]
    heat_mode  = task["heat_mode"]

    feed_temp_K   = float(feed_cfg["temperature_C"]) + 273.15
    feed_press    = float(feed_cfg["pressure_bar"]) * 1e5
    outlet_temp_K = float(outlet_cfg["temperature_C"]) + 273.15
    dp_bar        = float(outlet_cfg.get("pressure_drop_bar", 0.0))
    feed_flow     = float(feed_cfg.get("flow_kmol_h", 100.0)) * 1000 / 3600  # mol/s

    comp_dict = {k: float(v) for k, v in task["components"].items()}

    # Material streams
    feed_obj   = sim.AddObject(ObjectType.MaterialStream,  50, 300, "FEED").GetAsObject()
    outlet_obj = sim.AddObject(ObjectType.MaterialStream, 450, 300, "OUT" ).GetAsObject()

    # Energy stream
    e1 = sim.AddObject(ObjectType.EnergyStream, 250, 450, "E1").GetAsObject()

    # Unit op — Heater and Cooler are the same DWSIM type; mode is set via CalcMode
    uo = sim.AddObject(ObjectType.Heater, 250, 300,
                       "Heater" if heat_mode == "heater" else "Cooler").GetAsObject()

    # Configure feed stream
    feed_obj.SetTemperature(feed_temp_K)
    feed_obj.SetPressure(feed_press)
    feed_obj.SetMolarFlow(feed_flow)
    for comp_name in comp_names:
        mf = float(comp_dict.get(comp_name, 0.0))
        feed_obj.SetOverallCompoundMolarFlow(comp_name, mf * feed_flow)

    # Configure unit op
    uo.CalcMode = DWSIMUnitOps.Heater.CalculationMode.OutletTemperature
    uo.OutletTemperature = outlet_temp_K
    uo.DeltaP = dp_bar * 1e5

    print(f"[heat_master] {heat_mode.capitalize()}: "
          f"{feed_temp_K - 273.15:.1f} C → {outlet_temp_K - 273.15:.1f} C, "
          f"dP = {dp_bar:.3f} bar")

    # Wire: FEED → Heater/Cooler → OUT; E1 → Heater/Cooler
    sim.ConnectObjects(feed_obj.GraphicObject, uo.GraphicObject,     -1, -1)
    sim.ConnectObjects(uo.GraphicObject,       outlet_obj.GraphicObject, -1, -1)
    sim.ConnectObjects(e1.GraphicObject,       uo.GraphicObject,     -1, -1)
    sim.AutoLayout()

    # Solve
    Settings.SolverMode = 0
    errors = interf.CalculateFlowsheet4(sim)
    if errors is not None and len(errors) > 0:
        raise RuntimeError("[heat_master] Solver errors:\n" +
                           "\n".join(str(e) for e in errors))

    print(f"[heat_master] {heat_mode.capitalize()} solved.")

    feed_result = _extract_stream(feed_obj, "FEED", comp_names)
    return feed_result, feed_obj, outlet_obj, uo


# ─────────────────────────────────────────────────────────────────────────────
#  DUTY CALCULATOR  (enthalpy balance — same approach as test_heat_exchanger.py)
# ─────────────────────────────────────────────────────────────────────────────

def _calc_duty(uo_obj) -> dict:
    """
    Reads heat duty directly from the solved DWSIM heater/cooler object.
    DeltaQ is in W; positive = heat added (heater), negative = heat removed (cooler).
    """
    try:
        Q_kW = float(uo_obj.DeltaQ)
    except Exception:
        Q_kW = 0.0
    return {
        "duty_kW":  round(Q_kW, 4),
        "duty_kJh": round(Q_kW * 3600, 2),
        "duty_MWh": round(Q_kW / 1000, 6),
    }


# ─────────────────────────────────────────────────────────────────────────────
#  MAIN RUNNER — called by llm2_orchestrator.py
# ─────────────────────────────────────────────────────────────────────────────

def run_heat_master(task: dict, output_block_fn, output_dir: str = OUTPUT_DIR):
    """
    Full pipeline: init DWSIM → build topology → solve → call output_block_fn.

    Parameters
    ----------
    task             : dict   parsed task JSON from LLM #1
    output_block_fn  : callable(results: dict) → None
    output_dir       : str    where to save .dwxmz files

    The results dict passed to output_block_fn:
    {
        "heat_mode":        "heater" | "cooler",
        "property_package": str,
        "components":       list[str],
        "feed":             stream dict,
        "outlet":           stream dict,
        "duty": {
            "duty_kW":  float,   # positive = heat added, negative = heat removed
            "duty_kJh": float,
            "duty_MWh": float,
        }
    }
    Each stream dict: stream, T_K, T_C, P_Pa, P_bar,
                      molar_flow_molh, mass_flow_kgh,
                      enthalpy_kJkmol, vapor_fraction, x_<CompName>, ...
    """
    import pythoncom
    pythoncom.CoInitialize()

    from simquery.core.dwsim_core import (
        init_dwsim, create_flowsheet, select_property_package, save_flowsheet,
    )

    comp_dict  = {k: float(v) for k, v in task["components"].items()}
    comp_list  = list(comp_dict.keys())
    heat_mode  = task["heat_mode"]

    raw_pkg = task.get("property_package")
    pkg_tag = _normalize_package(raw_pkg) if raw_pkg else _auto_select_package(comp_list)

    interf = init_dwsim(DWSIM_PATH)
    sim    = create_flowsheet(interf)

    for comp in comp_list:
        sim.AddCompound(comp)
    comp_names = list(sim.SelectedCompounds.Keys)

    select_property_package(sim, pkg_tag)

    feed_result, feed_obj, outlet_obj, uo_obj = _build_heat(
        task, interf, sim, comp_names, pkg_tag
    )

    outlet_result = _extract_stream(outlet_obj, "OUT", comp_names)
    duty          = _calc_duty(uo_obj)

    results = {
        "heat_mode":        heat_mode,
        "property_package": pkg_tag,
        "components":       comp_names,
        "feed":             feed_result,
        "outlet":           outlet_result,
        "duty":             duty,
    }

    os.makedirs(output_dir, exist_ok=True)
    tag = "_".join(comp_list)
    save_flowsheet(interf, sim,
                   os.path.join(output_dir, f"{heat_mode}_{tag}.dwxmz"))

    output_block_fn(results)


# ─────────────────────────────────────────────────────────────────────────────
#  CLI  (for manual testing)
# ─────────────────────────────────────────────────────────────────────────────

def _default_output_block(results: dict):
    print("\n" + "=" * 60)
    print(f"HEAT RESULTS ({results['heat_mode'].upper()}, {results['property_package']})")
    print("=" * 60)
    for key in ("feed", "outlet"):
        s = results[key]
        print(f"\n  {s['stream']}")
        print(f"    T = {s['T_C']:.2f} C  |  P = {s['P_bar']:.3f} bar  "
              f"|  V_frac = {s['vapor_fraction']:.4f}  "
              f"|  flow = {s['molar_flow_molh']:.2f} mol/h  "
              f"|  H = {s['enthalpy_kJkmol']:.1f} kJ/kmol")
        for k, v in s.items():
            if k.startswith("x_"):
                print(f"      {k} = {v:.6f}")
    d = results["duty"]
    label = "added" if d["duty_kW"] >= 0 else "removed"
    print(f"\n  Heat duty ({label}) : {abs(d['duty_kW']):.2f} kW  "
          f"({abs(d['duty_kJh']):.1f} kJ/h)")
    print("=" * 60)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Heat master template — run with a task JSON for testing."
    )
    parser.add_argument("task_json", help="Path to task JSON file")
    args = parser.parse_args()

    with open(args.task_json, "r") as f:
        task = json.load(f)

    run_heat_master(task, _default_output_block)

