"""
DWSIM_ry_test/tasks/flash_master.py
=====================================
Master flash template — used by LLM #2 code-generation pipeline.

The top section (DWSIM init → component loading → topology wiring → solve)
is FIXED and never touched by LLM #2.

The bottom section (marked OUTPUT BLOCK) is generated by LLM #2 at runtime
and injected here to answer exactly what the user asked for.

Supported flash modes:
  - isothermal_PT_flash  :  FEED → Flash1 → V + L   (drum T and P both fixed)
  - adiabatic_PT_flash   :  FEED → Valve → Flash1 → V + L  (only drum P fixed, Q=0)

Input JSON format (from LLM #1 / orchestrator_ft.py):
{
  "task_type":        "flash",
  "flash_mode":       "isothermal_PT_flash" | "adiabatic_PT_flash",
  "components":       {"Propane": 0.5, "n-Butane": 0.5},
  "feed": {
    "flow_kmol_h":    100.0,
    "temperature_C":  60.0,
    "pressure_bar":   12.0
  },
  "flash_drum": {
    "temperature_C":  60.0,    ← isothermal only
    "pressure_bar":   6.0
  },
  "property_package": "PR",
  "user_request":     "<original user question>"   ← added by llm2_orchestrator.py
}

CLI usage (for testing without LLM #2):
  python DWSIM_ry_test/tasks/flash_master.py <path_to_task.json>

When used via LLM #2, this file is never called directly — llm2_orchestrator.py
injects the OUTPUT BLOCK, writes a temp script, and executes it.
"""

import json
import os
import sys
import argparse

# ─────────────────────────────────────────────────────────────────────────────
#  PATH SETUP
# ─────────────────────────────────────────────────────────────────────────────
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.abspath(os.path.join(_HERE, "..", ".."))
sys.path.insert(0, _ROOT)

DWSIM_PATH = r"C:\Users\terrbear\AppData\Local\DWSIM"
OUTPUT_DIR  = os.path.join(_ROOT, "output")

PACKAGE_ALIASES = {
    "PENG-ROBINSON": "PR", "PENGROBINSON": "PR", "PENG ROBINSON": "PR",
    "PR": "PR", "NRTL": "NRTL", "SRK": "SRK",
    "SOAVE-REDLICH-KWONG": "SRK", "UNIQUAC": "UNIQUAC",
    "IDEAL": "IDEAL", "RAOULT": "IDEAL",
    "STEAM": "STEAM", "STEAM TABLES": "STEAM",
}

POLAR_COMPONENTS = {
    "WATER", "ETHANOL", "METHANOL", "ACETONE", "ACETIC ACID",
    "ISOPROPANOL", "1-PROPANOL", "N-PROPANOL",
}


def _normalize_package(pkg_str: str) -> str:
    key = pkg_str.upper().replace("-", "").replace(" ", "")
    for alias_key, val in PACKAGE_ALIASES.items():
        if alias_key.replace("-", "").replace(" ", "") == key:
            return val
    return pkg_str


def _auto_select_package(comp_list: list) -> str:
    if any(c.upper() in POLAR_COMPONENTS for c in comp_list):
        return "NRTL"
    return "PR"


# ─────────────────────────────────────────────────────────────────────────────
#  STREAM RESULT EXTRACTOR  (available to LLM #2 output block)
# ─────────────────────────────────────────────────────────────────────────────

def _extract_stream(stream_obj, stream_name: str, comp_names: list) -> dict:
    """
    Pull T, P, molar flow, vapor fraction, and per-component mole fractions
    from a solved DWSIM MaterialStream.

    Returns a flat dict:
    {
        "stream":           "V",
        "T_K":              333.15,
        "T_C":              60.0,
        "P_Pa":             600000.0,
        "P_bar":            6.0,
        "molar_flow_molh":  62340.0,
        "vapor_fraction":   1.0,
        "x_Propane":        0.72,
        "x_n-Butane":       0.28
    }
    """
    def _get(val):
        if val is None:
            return 0.0
        try:
            return float(val)
        except TypeError:
            try:
                return float(val.GetValueOrDefault())
            except Exception:
                return 0.0

    p0 = stream_obj.Phases[0].Properties
    p2 = stream_obj.Phases[2].Properties

    result = {
        "stream":          stream_name,
        "T_K":             round(_get(p0.temperature), 4),
        "T_C":             round(_get(p0.temperature) - 273.15, 4),
        "P_Pa":            round(_get(p0.pressure), 2),
        "P_bar":           round(_get(p0.pressure) / 1e5, 4),
        "molar_flow_molh": round(_get(p0.molarflow) * 3600, 4),
        "vapor_fraction":  round(_get(p2.molarfraction), 6),
    }

    for comp_name in comp_names:
        try:
            xval = _get(stream_obj.Phases[0].Compounds[comp_name].MoleFraction)
        except Exception:
            xval = 0.0
        result[f"x_{comp_name}"] = round(xval, 6)

    return result


# ─────────────────────────────────────────────────────────────────────────────
#  FIXED TOPOLOGY: ISOTHERMAL PT FLASH
#  FEED → Flash1 → V + L   (drum T and P both set from JSON)
# ─────────────────────────────────────────────────────────────────────────────

def _build_isothermal(task: dict, interf, sim, comp_names: list, pkg_tag: str):
    """
    Builds and wires the isothermal PT flash flowsheet.
    Returns (feed_obj, vapor_obj, liquid_obj) — all solved after this call.
    """
    from DWSIM.Interfaces.Enums.GraphicObjects import ObjectType
    from DWSIM.GlobalSettings import Settings

    feed_cfg  = task["feed"]
    drum_cfg  = task["flash_drum"]

    feed_temp_K  = float(feed_cfg["temperature_C"]) + 273.15
    feed_press   = float(feed_cfg["pressure_bar"]) * 1e5
    drum_temp_K  = float(drum_cfg["temperature_C"]) + 273.15
    drum_press   = float(drum_cfg["pressure_bar"]) * 1e5
    feed_flow    = float(feed_cfg.get("flow_kmol_h", 100.0)) * 1000 / 3600  # mol/s

    comp_dict = {k: float(v) for k, v in task["components"].items()}

    # Material streams
    feed_obj   = sim.AddObject(ObjectType.MaterialStream,  50, 300, "FEED").GetAsObject()
    vapor_obj  = sim.AddObject(ObjectType.MaterialStream, 400, 100, "V"   ).GetAsObject()
    liquid_obj = sim.AddObject(ObjectType.MaterialStream, 400, 500, "L"   ).GetAsObject()

    # Energy stream
    e1 = sim.AddObject(ObjectType.EnergyStream, 250, 500, "E1").GetAsObject()

    # Flash drum
    flash_uo = sim.AddObject(ObjectType.Vessel, 250, 300, "Flash1").GetAsObject()

    # Set feed to DRUM conditions (Vessel inherits T and P from inlet)
    feed_obj.SetTemperature(drum_temp_K)
    feed_obj.SetPressure(drum_press)
    feed_obj.SetMolarFlow(feed_flow)
    for comp_name in comp_names:
        mf = float(comp_dict.get(comp_name, 0.0))
        feed_obj.SetOverallCompoundMolarFlow(comp_name, mf * feed_flow)

    print(f"[flash_master] Isothermal: drum {drum_temp_K - 273.15:.1f} C, "
          f"{drum_press / 1e5:.2f} bar")

    # Wire
    sim.ConnectObjects(feed_obj.GraphicObject,  flash_uo.GraphicObject,   -1, -1)
    sim.ConnectObjects(flash_uo.GraphicObject,  vapor_obj.GraphicObject,  -1, -1)
    sim.ConnectObjects(flash_uo.GraphicObject,  liquid_obj.GraphicObject, -1, -1)
    sim.ConnectObjects(e1.GraphicObject,        flash_uo.GraphicObject,   -1, -1)
    sim.AutoLayout()

    # Solve
    Settings.SolverMode = 0
    errors = interf.CalculateFlowsheet4(sim)
    if errors is not None and len(errors) > 0:
        raise RuntimeError("[flash_master] Solver errors:\n" +
                           "\n".join(str(e) for e in errors))

    print("[flash_master] Isothermal flash solved.")

    # Patch FEED stream to show original feed conditions (not drum conditions)
    feed_result = _extract_stream(feed_obj, "FEED", comp_names)
    feed_result["T_K"]   = round(feed_temp_K, 4)
    feed_result["T_C"]   = round(feed_temp_K - 273.15, 4)
    feed_result["P_Pa"]  = round(feed_press, 2)
    feed_result["P_bar"] = round(feed_press / 1e5, 4)

    return feed_result, feed_obj, vapor_obj, liquid_obj


# ─────────────────────────────────────────────────────────────────────────────
#  FIXED TOPOLOGY: ADIABATIC PT FLASH
#  FEED → Valve → Flash1 → V + L   (pressure drop across valve, Q=0 on drum)
# ─────────────────────────────────────────────────────────────────────────────

def _build_adiabatic(task: dict, interf, sim, comp_names: list, pkg_tag: str):
    """
    Builds and wires the adiabatic PT flash flowsheet.
    Returns (feed_result_dict, feed_obj, valve_out_obj, vapor_obj, liquid_obj).
    """
    from DWSIM.Interfaces.Enums.GraphicObjects import ObjectType
    from DWSIM.UnitOperations import UnitOperations as DWSIMUnitOps
    from DWSIM.GlobalSettings import Settings

    feed_cfg = task["feed"]
    drum_cfg = task["flash_drum"]

    feed_temp_K = float(feed_cfg["temperature_C"]) + 273.15
    feed_press  = float(feed_cfg["pressure_bar"]) * 1e5
    drum_press  = float(drum_cfg["pressure_bar"]) * 1e5
    feed_flow   = float(feed_cfg.get("flow_kmol_h", 100.0)) * 1000 / 3600  # mol/s

    comp_dict = {k: float(v) for k, v in task["components"].items()}

    # Material streams
    feed_obj     = sim.AddObject(ObjectType.MaterialStream,  50, 300, "FEED"    ).GetAsObject()
    valve_out    = sim.AddObject(ObjectType.MaterialStream, 250, 300, "VALVE_OUT").GetAsObject()
    vapor_obj    = sim.AddObject(ObjectType.MaterialStream, 500, 100, "V"       ).GetAsObject()
    liquid_obj   = sim.AddObject(ObjectType.MaterialStream, 500, 500, "L"       ).GetAsObject()

    # Energy stream (flash drum)
    e1 = sim.AddObject(ObjectType.EnergyStream, 400, 500, "E1").GetAsObject()

    # Unit operations
    valve_uo = sim.AddObject(ObjectType.Valve,  150, 300, "Valve1").GetAsObject()
    flash_uo = sim.AddObject(ObjectType.Vessel, 400, 300, "Flash1").GetAsObject()

    # Configure feed
    feed_obj.SetTemperature(feed_temp_K)
    feed_obj.SetPressure(feed_press)
    feed_obj.SetMolarFlow(feed_flow)
    for comp_name in comp_names:
        mf = float(comp_dict.get(comp_name, 0.0))
        feed_obj.SetOverallCompoundMolarFlow(comp_name, mf * feed_flow)

    # Configure valve: isenthalpic expansion to drum pressure
    valve_uo.OutletPressure = drum_press
    valve_uo.CalcMode = DWSIMUnitOps.Valve.CalculationMode.OutletPressure

    print(f"[flash_master] Adiabatic: feed {feed_temp_K - 273.15:.1f} C → "
          f"valve → {drum_press / 1e5:.2f} bar drum")

    # Wire: FEED → Valve → VALVE_OUT → Flash1 → V / L
    sim.ConnectObjects(feed_obj.GraphicObject,  valve_uo.GraphicObject,  -1, -1)
    sim.ConnectObjects(valve_uo.GraphicObject,  valve_out.GraphicObject, -1, -1)
    sim.ConnectObjects(valve_out.GraphicObject, flash_uo.GraphicObject,  -1, -1)
    sim.ConnectObjects(flash_uo.GraphicObject,  vapor_obj.GraphicObject, -1, -1)
    sim.ConnectObjects(flash_uo.GraphicObject,  liquid_obj.GraphicObject,-1, -1)
    sim.ConnectObjects(e1.GraphicObject,        flash_uo.GraphicObject,  -1, -1)
    sim.AutoLayout()

    # Solve
    Settings.SolverMode = 0
    errors = interf.CalculateFlowsheet4(sim)
    if errors is not None and len(errors) > 0:
        raise RuntimeError("[flash_master] Solver errors:\n" +
                           "\n".join(str(e) for e in errors))

    print("[flash_master] Adiabatic flash solved.")

    feed_result = _extract_stream(feed_obj, "FEED", comp_names)
    return feed_result, feed_obj, valve_out, vapor_obj, liquid_obj


# ─────────────────────────────────────────────────────────────────────────────
#  MAIN RUNNER — called by llm2_orchestrator.py after OUTPUT BLOCK is injected
# ─────────────────────────────────────────────────────────────────────────────

def run_flash_master(task: dict, output_block_fn, output_dir: str = OUTPUT_DIR):
    """
    Full pipeline: init DWSIM → build topology → solve → call output_block_fn.

    Parameters
    ----------
    task             : dict   parsed task JSON from LLM #1
    output_block_fn  : callable(results: dict) → None
                       Generated by LLM #2. Receives a results dict and
                       prints / saves whatever the user asked for.
    output_dir       : str    where to save .dwxmz files

    The results dict passed to output_block_fn contains:
    {
        "flash_mode":       str,
        "property_package": str,
        "components":       list of component name strings,
        "feed":             stream dict from _extract_stream(),
        "vapor":            stream dict from _extract_stream(),
        "liquid":           stream dict from _extract_stream(),
        "valve_out":        stream dict  ← adiabatic only, else None
    }
    Each stream dict keys: stream, T_K, T_C, P_Pa, P_bar,
                           molar_flow_molh, vapor_fraction, x_<CompName>, ...
    """
    import pythoncom
    pythoncom.CoInitialize()

    from DWSIM_ry_test.lib.dwsim_core import (
        init_dwsim, create_flowsheet, select_property_package, save_flowsheet,
    )

    comp_dict = {k: float(v) for k, v in task["components"].items()}
    comp_list = list(comp_dict.keys())
    flash_mode = task["flash_mode"]

    raw_pkg = task.get("property_package")
    pkg_tag = _normalize_package(raw_pkg) if raw_pkg else _auto_select_package(comp_list)

    # Init DWSIM
    interf = init_dwsim(DWSIM_PATH)
    sim    = create_flowsheet(interf)

    for comp in comp_list:
        sim.AddCompound(comp)
    comp_names = list(sim.SelectedCompounds.Keys)

    select_property_package(sim, pkg_tag)

    # Build topology
    valve_out_result = None

    if flash_mode == "isothermal_PT_flash":
        feed_result, feed_obj, vapor_obj, liquid_obj = _build_isothermal(
            task, interf, sim, comp_names, pkg_tag
        )
    elif flash_mode == "adiabatic_PT_flash":
        feed_result, feed_obj, valve_out_obj, vapor_obj, liquid_obj = _build_adiabatic(
            task, interf, sim, comp_names, pkg_tag
        )
        valve_out_result = _extract_stream(valve_out_obj, "VALVE_OUT", comp_names)
    else:
        raise ValueError(f"[flash_master] Unsupported flash_mode: '{flash_mode}'")

    # Extract results into plain dicts
    results = {
        "flash_mode":       flash_mode,
        "property_package": pkg_tag,
        "components":       comp_names,
        "feed":             feed_result,
        "vapor":            _extract_stream(vapor_obj,  "V", comp_names),
        "liquid":           _extract_stream(liquid_obj, "L", comp_names),
        "valve_out":        valve_out_result,
    }

    # Save flowsheet
    os.makedirs(output_dir, exist_ok=True)
    tag = "_".join(comp_list)
    save_flowsheet(interf, sim,
                   os.path.join(output_dir, f"{flash_mode}_{tag}.dwxmz"))

    # ── LLM #2 OUTPUT BLOCK ──────────────────────────────────────────────────
    # output_block_fn is injected by llm2_orchestrator.py.
    # It receives `results` and produces the user-facing output.
    # ─────────────────────────────────────────────────────────────────────────
    output_block_fn(results)


# ─────────────────────────────────────────────────────────────────────────────
#  CLI  (for manual testing — uses a default print-everything output block)
# ─────────────────────────────────────────────────────────────────────────────

def _default_output_block(results: dict):
    """Fallback: print everything. Used when running from CLI without LLM #2."""
    import json
    print("\n" + "=" * 60)
    print("FLASH RESULTS (default output — all streams)")
    print("=" * 60)
    for key in ("feed", "valve_out", "vapor", "liquid"):
        s = results.get(key)
        if s is None:
            continue
        print(f"\n  {s['stream']}")
        print(f"    T = {s['T_C']:.2f} C  |  P = {s['P_bar']:.3f} bar  "
              f"|  V_frac = {s['vapor_fraction']:.4f}  "
              f"|  flow = {s['molar_flow_molh']:.2f} mol/h")
        for k, v in s.items():
            if k.startswith("x_"):
                print(f"      {k} = {v:.6f}")
    print("=" * 60)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Flash master template — run with a task JSON for testing."
    )
    parser.add_argument("task_json", help="Path to task JSON file (LLM #1 format)")
    args = parser.parse_args()

    with open(args.task_json, "r") as f:
        task = json.load(f)

    run_flash_master(task, _default_output_block)
